name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: say Hello World!
      id: say-hello-world
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: say Hello World!
        setup-command: ''
        command: gradle test sayHelloWorld
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAY-HELLO-WORLD_RESULTS: "${{steps.say-hello-world.outputs.result}}"
      with:
        runners: say-hello-world
